### ISSUE TITLE
thread_local dependency conflict

### ISSUE THREAD

**Issue by nuxeh** [cardoe/stderrlog-rs#20]
Hello, is there a reason for the `thread_local` dependency being this...
https://github.com/cardoe/stderrlog-rs/blob/678f929c28ec170fe4597de798a9664839fb385f/Cargo.toml#L27

I get dependency conflicts using the latest `regex`:

```
error: failed to select a version for `thread_local`.
    ... required by package `stderrlog v0.4.3`
    ... which is depended on by `url-bot-rs v0.2.2 (/home/ed/git/url-bot-rs)`
versions that meet the requirements `^0.3, <= 0.3.4` are: 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0

all possible versions conflict with previously selected packages.

  previously selected package `thread_local v0.3.6`
    ... which is depended on by `regex v1.3.1`
    ... which is depended on by `url-bot-rs v0.2.2 (/home/ed/git/url-bot-rs)`

failed to select a version for `thread_local` which could resolve this conflict
```

**Comment by vincentdephily** [comment]
Same issue with `atty` dependency. The `<= x.y.z` restriction was added by https://github.com/cardoe/stderrlog-rs/commit/872ac8ec789767c17dae88736e622871de9cf36c which doesn't seem to document a reason for the restriction.

For what it's worth, for my project cargo apparently (according to `cargo tree`) decides to use the latest `atty` and `thread_local` anyway, and I don't see any atty-related stderrlog bug. But some commands like `cargo outdated` still fail because of the dep conflict.

Unless you have a documented failure with latest `atty/thread_local`, I suggest depending simply on `atty="0.2"` and `thread_local="0.3"`.
